---
name: Lingua-AIN-Romanize
version: 0.0.1
author:
  - 'OHTSUKA Ko-hei <nene@kokogiko.net>'
abstract: Convert Aynu language between roman characters and Kana characters.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Lingua::JA::Kana: 0.04
  Test::Base: 0
  version: 0
provides:
  Lingua::AIN::Romanize:
    file: lib/Lingua/AIN/Romanize.pm
    version: 0.0.1
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
